'':
  - type: TXT
    value: google-site-verification=8Opi-daQRYsKbKRxiU6ra5zvFHyEjllVcyXpIK5-xxQ

hack:
  - ttl: 1800
    type: MX
    values:
      - exchange: aspmx.l.google.com.
        preference: 1
      - exchange: alt1.aspmx.l.google.com.
        preference: 5
      - exchange: alt2.aspmx.l.google.com.
        preference: 5
      - exchange: alt3.aspmx.l.google.com.
        preference: 10
      - exchange: alt4.aspmx.l.google.com.
        preference: 10
  - octodns:
      cloudflare:
        proxied: true
    type: CNAME
    value: hheu.github.io.
  - ttl: 1800
    type: TXT
    value: v=spf1 include:_spf.google.com ~all

you:
  type: TXT
  value: hack.athon.uk <3 you
